{% set name = "aoe2netwrapper" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aoe2netwrapper-{{ version }}.tar.gz
  sha256: e6d7b2b56bf673b6dc39bd0ce9726750ca6f0d267f5d1068d008bde951ddae3a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - loguru >=0.5.3,<0.6.0
    - pydantic >=1.7.3,<2.0.0
    - python >={{ python_min }},<4.0
    - requests >=2.25.1,<3.0.0

test:
  imports:
    - aoe2netwrapper
    - aoe2netwrapper.models
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fsoubelet/AoE2NetAPIWrapper
  summary: Python wrapper for the aoe2.net data API
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A simple, efficient and typed wrapper to query the https://aoe2.net APIs with Python 3.6.1+
  doc_url: https://fsoubelet.github.io/AoE2NetAPIWrapper/

extra:
  recipe-maintainers:
    - fsoubelet
